import React from 'react'

import type { Metadata } from 'next'
import localFont from 'next/font/local'

import './globals.css'

const pretendard = localFont({
  src: '../styles/pretendard-variable.ttf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className={pretendard.className}>{children}</body>
    </html>
  )
}
